pipeline {
    agent any
    stages {
        stage('Building The Project') {
            steps {
               sh script: '''
                chmod 777 ./gradlew
                ./gradlew build
                ''',
                label: "Building Project"
            }
        }
        stage('Running the Tests') {
            steps {
                sh script: '''
                    ./gradlew test
                ''',
                label: "Building Project"
            }
        }
        stage('Static Code Analysis') {
            steps {
                echo 'Using sonarQube to do static code analysis'
                sh "  ./gradlew sonarqube \
                      -Dsonar.projectKey=tavisca-ekhan_rover \
                      -Dsonar.organization=tavisca-ekhan \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.login=42beb5da44e86970b0cc91f2e0b81d9b5fb2180d"
            }
        }
        stage('Deploying') {
            steps {
                sh script: '''
                    echo 'Building the docker image with Dockerfile'
                    docker build -t "rover" -f .infra/docker/Dockerfile .
                '''
            }
        }
        stage('Publishing to Dockerhub') {
            steps {
                echo "Pushing the image to docker hub"
                sh "docker login -u ebrank97 -p abc123!@#"
                sh "docker tag rover:latest ebrank97/rover:latest"
                sh "docker push ebrank97/rover:latest"
            }
        }
    }
}
